name: Jira

on:
  workflow_call:
    secrets:
      VR_PACKAGE_TOKEN:
        required: true
      JIRA_BASE_URL:
        required: true
      JIRA_USER_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true

jobs:

  get-task:
    # name: Get taks on jira
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find in commit messages
      uses: atlassian/gajira-find-issue-key@v3
      with:
        from: ${{ github.event.ref }}


    - name: Fetch Jira Issue
      id: fetch_jira_issue
      run: |
        # Recupere as variáveis de ambiente
        JIRA_USERNAME=${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN }}
        JIRA_BASE_URL=${{ secrets.JIRA_BASE_URL }}
        JIRA_ISSUE_KEY=MOB-1094
        JIRA_FIELDS="summary,customfield_10037"

        # Faça uma solicitação à API do Jira para buscar a tarefa
        ISSUE_JSON=$(curl -s -u $JIRA_USERNAME:$JIRA_API_TOKEN \
          -X GET "$JIRA_BASE_URL/rest/api/2/issue/$JIRA_ISSUE_KEY?fields=$JIRA_FIELDS")

        # Exiba os detalhes da tarefa no console
        echo "$ISSUE_JSON"

        echo "::set-output name=TITLE::$(echo $ISSUE_JSON | jq -r '.fields.summary')"
        echo "::set-output name=DOC_INFO::$(echo $ISSUE_JSON | jq -r '.fields.customfield_10037')"
        

    - name: ECHO Jira Issue
      run: |
        TITLE="${{ steps.fetch_jira_issue.outputs.TITLE }}"
        DOC_INFO="${{ steps.fetch_jira_issue.outputs.DOC_INFO }}"

        echo "$TITLE"
        echo "$DOC_INFO"
        
    #     - name: Checkout
    #       uses: actions/checkout@v3

    #     - name: Login
    #       uses: atlassian/gajira-login@master
    #       env:
    #         JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
    #         JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
    #         JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

        # - name: Setup
        #   uses: atlassian/gajira-cli@v3
        #   with:
        #     version: 1.0.27

        # - name: Find in commit messages
        #   uses: atlassian/gajira-find-issue-key@v3
        #   with:
        #     from: branch

        # - name: Create TODO
        #   uses: atlassian/gajira-todo@v3
        #   with:
        #     project: MC
        #     issuetype: Task
        #     description: Created automatically via GitHub Actions
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # - name: Transition issue
        #   uses: atlassian/gajira-transition@master
        #   with:
        #     issue: ${{ steps.create.outputs.issue }}
        #     transition: "In Progress"

        # - name: Exibir Descrição Capturada
        #   run: |
        #     jira view MOB-1094 -t debug
        #     # echo "A descrição da tarefa Jira é: ${{ steps.capture-description.outputs.issueDescription }}"
