name: Jira

on:
  workflow_call:
    secrets:
      VR_PACKAGE_TOKEN:
        required: true
      JIRA_BASE_URL:
        required: true
      JIRA_USER_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true

jobs:
  get-task:
    # name: Get taks on jira
    runs-on: ubuntu-latest

    steps:
    #     - name: Checkout
    #       uses: actions/checkout@v3

    #     - name: Login
    #       uses: atlassian/gajira-login@master
    #       env:
    #         JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
    #         JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
    #         JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Jira Description
        id: jira_description
        uses: cakeinpanic/jira-description-action@v0.5.1
        with:
          github-token: ${{ secrets.VR_PACKAGE_TOKEN }}
          jira-token: ${{ secrets.JIRA_API_TOKEN }}
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}
          custom-issue-number-regexp: '^\d+'
          jira-project-key: 'MOB-1094'
      
      - name: ISSUE KEY
        run: |
          ISSUE_KEY=${{ steps.jira_description.outputs.jira-issue-found }}
          echo "jira issue $ISSUE_KEY"

        # - name: Setup
        #   uses: atlassian/gajira-cli@v3
        #   with:
        #     version: 1.0.27

        # - name: Find in commit messages
        #   uses: atlassian/gajira-find-issue-key@v3
        #   with:
        #     from: branch

        # - name: Create TODO
        #   uses: atlassian/gajira-todo@v3
        #   with:
        #     project: MC
        #     issuetype: Task
        #     description: Created automatically via GitHub Actions
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # - name: Transition issue
        #   uses: atlassian/gajira-transition@master
        #   with:
        #     issue: ${{ steps.create.outputs.issue }}
        #     transition: "In Progress"

        # - name: Exibir Descrição Capturada
        #   run: |
        #     jira view MOB-1094 -t debug
        #     # echo "A descrição da tarefa Jira é: ${{ steps.capture-description.outputs.issueDescription }}"
