name: Jira

on:
  workflow_call:
    secrets:
      VR_PACKAGE_TOKEN:
        required: true
      JIRA_BASE_URL:
        required: true
      JIRA_USER_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true

jobs:
  get-task:
    name: Get taks on jira
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Login
          uses: atlassian/gajira-login@master
          env:
            JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
            JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
            JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

        - name: Find Issue Key
          uses: ./
          with:
            from: commits

        # - name: Transition issue
        #   uses: atlassian/gajira-transition@master
        #   with:
        #     issue: ${{ steps.create.outputs.issue }}
        #     transition: "In Progress"

        - name: Exibir Descrição Capturada
          run: |
            echo "A descrição da tarefa Jira é: ${{ steps.capture-description.outputs.issueDescription }}"
