name: Espelhar branch main.

on:
  workflow_call:
    secrets:
      VR_PACKAGE_TOKEN:
        required: true
    inputs:
      BRANCH:
        required: true
        type: string

jobs:
  leave-it-up-to-date:
    name: Espelhar branch main.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Git Config
        run: git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com" && git config --global user.name "${GITHUB_ACTOR}"

      - name: Verificar se a branch existe
        run: |
          BRANCH=${{ inputs.BRANCH }}

          if ! git rev-parse --verify $BRANCH; then
            # Se a branch não existir será criada
            git checkout -b $BRANCH origin/main
          fi

      - name: Atualizar a branch com a main
        run: |
          BRANCH=${{ inputs.BRANCH }}

          git fetch origin main
          git checkout $BRANCH
          git merge --ff-only origin/main
          git push origin $BRANCH
