name: Publish Release

on:
  workflow_dispatch:

jobs:
  run_pre_release:
    name: Run Pre Release
    uses: ./.github/workflows/pre-release.yml
    secrets:
      VR_PACKAGE_TOKEN: ${{ secrets.VRPACKAGETOKEN }}

  run_prepare_new_release:
    name: Run Prepare new release
    uses: ./.github/workflows/prepare-new-release.yaml
    secrets:
      VR_PACKAGE_TOKEN: ${{ secrets.VRPACKAGETOKEN }}
    with:
      LAST_VERSION: ${{ needs.run_pre_release.outputs.LAST_VERSION }}
      COMMIT_MESSAGES: ${{ needs.run_pre_release.outputs.COMMIT_MESSAGES }}

  # run_pre_release:
  #   name: Call Check Commit
  #   uses: ./.github/workflows/check-commits.yml
  #   needs:
  #    - run_pre_release
  #   secrets:
  #     VR_PACKAGE_TOKEN: ${{ secrets.VRPACKAGETOKEN }}

  # run_prepare_new_release:
  #   name: Call Generate release tag
  #   uses: ./.github/workflows/generate-release-tag.yml
  #   needs: run_pre_release
  #   if: needs.run_pre_release.outputs.HAS_CHANGES
  #   with:
  #     COMMIT_MESSAGES: ${{ needs.run_pre_release.outputs.COMMIT_MESSAGES }}
  #   secrets:
  #     VR_PACKAGE_TOKEN: ${{ secrets.VRPACKAGETOKEN }}
      

  prepare_branch_main:
    name: Prepare Branch Main
    if: github.ref == 'refs/heads/main' && needs.run_pre_release.outputs.HAS_CHANGES && ${{ always() }}
    needs: 
      - run_pre_release
      - run_prepare_new_release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.VRPACKAGETOKEN }}
          fetch-depth: 0
          ref: main

      - name: Git Config
        if: needs.run_prepare_new_release.outputs.HAS_RELEASE
        run: git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com" && git config --global user.name "${GITHUB_ACTOR}"

      - name: Upgrade Release
        id: upgrade_release
        if: needs.run_prepare_new_release.outputs.HAS_RELEASE
        run: |
          NEW_VERSION=${{ needs.run_prepare_new_release.outputs.NEW_VERSION }}

          npm --no-git-tag-version version $NEW_VERSION
          git add . 
          git commit -m "ci: Entrega da versão $NEW_VERSION"
          git push
      
  publish_release:
    name: Publish Release
    if: github.ref == 'refs/heads/main' && needs.run_pre_release.outputs.HAS_CHANGES && ${{ always() }}
    needs: 
      - run_pre_release
      - run_prepare_new_release
      - prepare_branch_main

    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.VRPACKAGETOKEN }}
          fetch-depth: 0
          ref: main

      - name: Create Release
        id: create_release
        if: needs.run_prepare_new_release.outputs.HAS_RELEASE
        uses: ncipollo/release-action@v1
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.VRPACKAGETOKEN }}
      #   with:
      #     tag_name: v${{ needs.run_prepare_new_release.outputs.NEW_VERSION }}
      #     release_name: Release v${{ needs.run_prepare_new_release.outputs.NEW_VERSION }}
      #     commit: main
        with:
          name: ${{ inputs.versao }}
          tag: v${{ inputs.versao }}
          commit: main
          draft: false
          prerelease: false
          token: ${{ secrets.VRPACKAGETOKEN }}

